name: master

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  tasks:
    runs-on: ubuntu-latest
    steps:
      - name: remote
        uses: appleboy/ssh-action@master
        with:
          host: 95.217.251.145
          username: root
          key: ${{ secrets.GITTHUB_SSH_KEY }}
          port: 22
          script: |
            cd /root/hi-hear/hi-gear-back        
            git pull origin master
            git checkout master
            sudo docker-compose down
            sudo docker-compose up -d --build
